### PR TITLE
Add configuration settings for Chicken Breeder and Roost speeds

### PR DESCRIPTION
**Pull request by benblank**
I found myself wanting to adjust the speed of Chicken Breeders for a modpack I'm working on, so created a configuration file for adjusting it.  (And also Roost speed, because it was easy.)  Both settings are floats which multiply the speed of the block (i.e. divide the time until next drop) and they can also be adjusted in the Mod Options GUI.

### CODE REVIEW

**Comment by timrwood** [comment]
Looks great, thanks!

I merged into https://github.com/timrwood/roost/tree/dev/1.3.0 and renamed `speedRoost` to `roostSpeed` so that it will group with other `roost` config values if they are added in the future.

**Comment by Bletch1971** [comment]
Hi, just did a build of the latest 1.3.0 branch and it fails when starting a server with this build. The configuration is causing the server to fail. The client seems to work fine with this version of the mod.

I built an earlier version of the 1.3.0 branch where you marked it as version bump, and it was working fine for both server and client.

**Comment by timrwood** [comment]
@Bletch1971, I made some changes to the way the config is generated using config annotations in https://github.com/timrwood/roost/commit/67b3c98363660e9c03acbe162b4fcb27a88a009e, can you see if the server is failing with those changes? I made that change a week or so ago, but forgot to push the changes until now.

**Comment by Bletch1971** [comment]
@timrwood, thank you for the update. I have downloaded the latest code from the 1.3.0 branch and I can confirm the configuration changes you have made are working on both my server and client.

I have also tested increasing the rates of the roost and breeder and they are working as expected.

NOTE: I changed the config values on the server from 1.0 to 10.0 for both the roost and breeder. BUT I left the client config values as the defaults (1.0). When I logged into the server, the higher rates were in effect (10.0).

I was not sure if the client would take the server or the client settings, but was pleased that I did not have to set the client config as well. And that the server config does override the client config.

Thank you for all the hard work. I look forward to the official 1.3.0 release and not using my janky 1.3.0 version :)

**Comment by timrwood** [comment]
I added an alpha release file to CurseForge, if everything looks good, I'll promote it to the official 1.3.0 release.

https://minecraft.curseforge.com/projects/roost/files/2635449

**Comment by Bletch1971** [comment]
@timrwood, you added a feature to show when the breeder is out of seeds.
Would it be possible to add a feature to show if the roost or breeder is full?

**Comment by Motziii** [comment]
Hello
idk if anyone is still here but how can i add it to my singleplayer

**Pull request merged**
